-record(feature,
        {
          name="",
          lookups=[]
         }).
-record(lookup,
        {
          name="",
          lookupflag="",
          lookups=[]
         }).
-record(lookuptable,
        {
          sub=[],
          by=[]
         }).
